version: "3.2"

services:
  backend:
    image: denoland/deno:1.12.0
    environment:
      - MONGO_URL=mongodb://mongodb
      - YAML_FILE=./test.yaml
    depends_on:
      - mongodb
    volumes:
      - type: bind
        source: .
        target: /usr/src
    ports:
      - 5000:5000
    command: >
      bash -c "cd /usr/src/backend
      && deno run --allow-read --allow-net index.ts"

  frontend:
    image: denoland/deno:1.12.0
    environment:
      - YAML_FILE=./test.yaml
    depends_on:
      - backend
    volumes:
      - type: bind
        source: .
        target: /usr/src
    ports:
      - 8080:8080
    command: >
      bash -c "cd /usr/src/frontend
      && deno run -A https://deno.land/x/aleph/install.ts
      && aleph dev"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    expose:
      - "27017"
    ports:
      - 4003:27017
    command: mongod --logpath=/dev/null
